export const ADD_FLOWER = 'ADD_FLOWER';
export const REMOVE_FLOWER = 'REMOVE_FLOWER';
export const SET_FLOWERS = 'SET_FLOWERS';
export const FETCH_FLOWERS_FAILED = 'FETCH_FLOWERS_FAILED';

export const PURCHASE_FLOWER_START = 'PURCHASE_FLOWER_START';
export const PURCHASE_FLOWER_SUCCESS = 'PURCHASE_FLOWER_SUCCESS';
export const PURCHASE_FLOWER_FAIL = 'PURCHASE_FLOWER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'ÁUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


